apiVersion: v1
kind: Service
metadata:  
  name: ecb-frontend
spec:
  selector:    
    app: ecb-frontend
  type: NodePort
  ports:  
  - port: 80
    targetPort: 80
    nodePort: 30009
---
apiVersion: v1
kind: Service
metadata:  
  name: getfiles
spec:
  selector:    
    app: getfiles
  type: LoadBalancer
  ports:  
  - name: getfiles
    port: 9659
    targetPort: 9659
---
apiVersion: v1
kind: Service
metadata:  
  name: publication
spec:
  selector:    
    app: publication
  type: LoadBalancer
  ports:  
  - port: 9658
    targetPort: 9658
---
apiVersion: v1
kind: Service
metadata:  
  name: userauth
spec:
  selector:    
    app: userauth
  type: LoadBalancer
  ports:  
  - port: 9656
    targetPort: 9656
---
apiVersion: v1
kind: Service
metadata:  
  name: userreg
spec:
  selector:    
    app: userreg
  type: LoadBalancer
  ports:  
  - port: 9654
    targetPort: 9654